export default Object.freeze({
  LOCATION_DETAILS: 'LocationDetails',
  LOCATION_EDIT: 'LocationEdit',
  LOCATION_REPORT: 'Add Report',
  REPORTS: 'Reports',
  REPORTS_EDIT: 'ReportsEdit',
  REPORTS_DETAILS: 'ReportDetails',
  QUESTIONS: 'Questions',
  CALENDAR: 'Calendar',
  QUESTION_DETAIL: 'QuestionDetail',
  QUESTION_EDIT: 'QuestionEdit',
  LOGIN: 'Login',
  MESSAGES: 'Messages',
  REGISTER: 'Register',
});
